name: Chorus CrabNebula Cloud Release
on:
    workflow_dispatch:
    push:
        branches:
            - release

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

env:
    CN_APPLICATION: "chorus/chorus"

jobs:
    draft:
        runs-on: ubuntu-22.04

        steps:
            - uses: actions/checkout@v4
              with:
                  lfs: true
            - name: create draft release
              uses: crabnebula-dev/cloud-release@v0
              with:
                  command: release draft ${{ env.CN_APPLICATION }} --framework tauri
                  api-key: ${{ secrets.CN_API_KEY }}

    build:
        needs: draft

        strategy:
            fail-fast: false
            matrix:
                include:
                    - os: macos-latest
                      architecture: aarch64-apple-darwin
                    - os: macos-latest
                      architecture: x86_64-apple-darwin
                    - os: windows-latest
                      architecture: x86_64-pc-windows-msvc

        runs-on: ${{ matrix.os }}

        steps:
            - uses: actions/checkout@v4
              with:
                  lfs: true
            - name: Install pnpm
              uses: pnpm/action-setup@v4
              with:
                  version: 9
            - uses: actions/setup-node@v4
              with:
                  node-version: "22"
            - name: Install stable toolchain
              uses: actions-rust-lang/setup-rust-toolchain@v1
              with:
                  toolchain: stable
                  cache: true

            - name: Install dependencies
              run: pnpm install --frozen-lockfile

            - name: Check formatting
              run: pnpm format:check

            # - name: Run ESLint
            #   run: pnpm lint

            - name: Build Tauri binaries for ${{ matrix.architecture }}
              run: |
                  rustup target add ${{ matrix.architecture }}
                  pnpm tauri build --target ${{ matrix.architecture }} --config src-tauri/tauri.conf.json
              env:
                  TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
                  TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}
                  APPLE_ID: ${{ runner.os == 'macOS' && secrets.APPLE_ID || '' }}
                  APPLE_PASSWORD: ${{ runner.os == 'macOS' && secrets.APPLE_PASSWORD || '' }}
                  APPLE_TEAM_ID: ${{ runner.os == 'macOS' && secrets.APPLE_TEAM_ID || '' }}
                  APPLE_CERTIFICATE: ${{ runner.os == 'macOS' && secrets.APPLE_CERTIFICATE || '' }}
                  APPLE_CERTIFICATE_PASSWORD: ${{ runner.os == 'macOS' && secrets.APPLE_CERTIFICATE_PASSWORD || '' }}
                  MELTY_DOWNLOADER_TOKEN: ${{ secrets.MELTY_DOWNLOADER_TOKEN }}

            - name: Upload assets for ${{ matrix.architecture }}
              uses: crabnebula-dev/cloud-release@v0
              with:
                  command: release upload ${{ env.CN_APPLICATION }} --framework tauri
                  api-key: ${{ secrets.CN_API_KEY }}
                  path: ./src-tauri
